// Original grade-8 lessons. Deterministic questions keep saved work stable.
const q=(id,prompt,answer,hint,explanation,accepted=[String(answer)])=>({id,prompt,answer:String(answer),accepted,hint,explanation});
const ex=(prompt,steps,answer)=>({prompt,steps,answer:String(answer)});
const pack=(id,title,objective,learn,examples,guided,practice,notebook)=>({id:`math-${id}`,grade:8,subject:'Math',title,objective,learn,examples,guided,practice,notebook});
const note=(prompt,sample)=>({prompt,checklist:['I stated the rule in my own words.','I showed the important steps, not just the answer.','I checked my result against the original problem.'],sample});
const power=(id,b,m,n)=>q(id,`Write ${b}^${m} × ${b}^${n} as ONE power. Use the format base^exponent; do not evaluate.`,`${b}^${m+n}`,'The base stays the same. Count how many copies of that base appear altogether.',`The first factor has ${m} copies of ${b} and the second has ${n}. That makes ${m+n} copies: ${b}^${m+n}.`);
const negative=(id,b,n)=>q(id,`Evaluate ${b}^${n}. Enter a number or fraction.`,n===0?'1':`1/${b**(-n)}`,'A zero exponent on a nonzero base gives 1. A negative exponent tells you to take a reciprocal.',n===0?`${b}^0 = 1: dividing ${b} by itself leaves 1, matching the exponent rule.`:`${b}^(${n}) = 1 / ${b}^${-n} = 1/${b**(-n)}. The negative exponent does not make the answer negative.`);
const notation=(id,value,coefficient,exp)=>q(id,`Write ${value} in scientific notation. Use the format ${'a x 10^n'} (for example, 4 x 10^3).`,`${coefficient} x 10^${exp}`,'Move the decimal until the first number is at least 1 but less than 10; then choose a power of ten that restores the original value.',`${coefficient} × 10^${exp} gives ${value}. ${exp>=0?'A positive exponent makes the value larger.':'A negative exponent makes the value smaller.'}`,[`${coefficient} x 10^${exp}`,`${coefficient} × 10^${exp}`,`${coefficient}*10^${exp}`,`${coefficient}e${exp}`]);
const equation=(id,a,b,c,x)=>{const d=(a-c)*x+b;return q(id,`Solve for x: ${a}x + ${b} = ${c}x + ${d}. Enter just the value of x.`,x,`Subtract ${c}x from BOTH sides first. Then undo the constant and the remaining coefficient.`,`Subtract ${c}x: ${a-c}x + ${b} = ${d}. Subtract ${b}: ${a-c}x = ${d-b}. Divide by ${a-c}: x = ${x}. Substitution gives ${a*x+b} on both sides.`);};
const slope=(id,x1,y1,x2,y2)=>q(id,`Find the slope of the line through (${x1}, ${y1}) and (${x2}, ${y2}). Enter a number or fraction.`,(y2-y1)/(x2-x1),'Subtract the y-values in one order. Subtract the x-values in that SAME order. Divide rise by run.',`m = (${y2} − ${y1}) / (${x2} − ${x1}) = ${y2-y1}/${x2-x1} = ${(y2-y1)/(x2-x1)}.`);
const model=(id,m,b,x,context)=>q(id,`${context} The model is y = ${m}x + ${b}. What is y when x = ${x}? Enter the number only.`,m*x+b,'The coefficient of x is the rate; the separate constant is the starting amount. Substitute x, multiply, then add.',`y = ${m}(${x}) + ${b} = ${m*x} + ${b} = ${m*x+b}. The starting amount is added once, not once for every unit of x.`);
const fun=(id,pairs,correct)=>q(id,`Does this set of ordered pairs represent a function? ${pairs.map(p=>`(${p[0]}, ${p[1]})`).join(', ')}. Enter yes or no.`,correct?'yes':'no','Inspect the FIRST coordinate (input) in each pair. Can any one input lead to two different outputs?',correct?'Every input has exactly one output. Different inputs may share an output; that still makes a function.':'At least one input is paired with two different outputs. That violates the definition of a function.');
const system=(id,a,b,c,d)=>{const x=(d-b)/(a-c),y=a*x+b;return q(id,`Solve the system: y = ${a}x + ${b} and y = ${c}x + ${d}. Enter x, y (for example, 2, 7).`,`${x}, ${y}`,'Both right sides equal y, so set them equal to each other. Solve for x, then substitute to find y.',`${a}x + ${b} = ${c}x + ${d}, so ${a-c}x = ${d-b} and x = ${x}. Then y = ${a}(${x}) + ${b} = ${y}. Both equations give the same point.`,[`${x}, ${y}`,`${x},${y}`,`(${x}, ${y})`,`(${x},${y})`]);};
const triangle=(id,a,b)=>{const c=Math.sqrt(a*a+b*b);return q(id,`A right triangle has legs ${a} cm and ${b} cm. Find the hypotenuse in cm. Enter just the number.`,c,'The hypotenuse is opposite the right angle. Square the legs, add their squares, then take the positive square root.',`c² = ${a}² + ${b}² = ${a*a+b*b}. The positive square root is ${c}, so c = ${c} cm. It is longer than either leg.`);};
const translation=(id,x,y,dx,dy)=>q(id,`Translate (${x}, ${y}) ${Math.abs(dx)} units ${dx>=0?'right':'left'} and ${Math.abs(dy)} units ${dy>=0?'up':'down'}. Enter the new coordinates as x, y.`,`${x+dx}, ${y+dy}`,'Horizontal movement changes x. Vertical movement changes y. Right/up add; left/down subtract.',`New x = ${x} ${dx>=0?'+':'−'} ${Math.abs(dx)} = ${x+dx}. New y = ${y} ${dy>=0?'+':'−'} ${Math.abs(dy)} = ${y+dy}. A translation slides a figure without turning or resizing it.`,[`${x+dx}, ${y+dy}`,`${x+dx},${y+dy}`,`(${x+dx}, ${y+dy})`,`(${x+dx},${y+dy})`]);

export const mathLessons=[
pack('exponent-products','Multiplying powers with the same base','Use the product rule to combine powers that have the same base.',[
 'An exponent counts repeated factors. In 5^3, the 5 is the base and the 3 is the exponent. This means 5 × 5 × 5, not 5 × 3. Writing out the factors helps you see what an exponent actually does.',
 'When you multiply powers with the same base, you join two groups of identical factors. For example, 5^2 × 5^3 contains two copies of 5 followed by three more. There are five copies altogether, so the result is 5^5.',
 'The product rule is b^m × b^n = b^(m+n). Keep the base and add the exponents. Do not multiply the bases or multiply the exponents. This rule works here because every repeated factor is the same.',
 'Check the operation before using the rule. It does not turn 5^2 + 5^3 into 5^5, and it does not combine 5^2 × 3^4 into a single power of 5. In this lesson, write answers as powers using the ^ symbol.'
],[ex('Combine 3^2 × 3^4.', ['The operation is multiplication and both bases are 3, so the product rule applies.','The first power has two factors of 3; the second has four. Together there are six factors.','Keep base 3 and add the exponents: 2 + 4 = 6.'],'3^6'),ex('Combine 10^3 × 10^2.', ['Both powers have base 10. Think of joining their repeated factors.','Three factors plus two factors gives five factors of 10.','Write 10^5. Checking numerically, 1,000 × 100 = 100,000.'],'10^5')],{...power('g',4,2,3),steps:['Check that both bases are identical.','Write down how many factors each exponent counts.','Add those counts and keep the original base.']},[[2,3,4],[7,2,5],[10,4,3],[6,1,4],[3,5,2],[8,3,3]].map((v,i)=>power(`p${i+1}`,...v)),note('Explain why 2^2 × 2^3 equals 2^5 rather than 4^6. Write out the factors to support your explanation.','2^2 has two factors of 2 and 2^3 has three. The product has five factors of 2, so it is 2^5. The base does not change because all five factors are still 2.')),
pack('zero-negative-exponents','Zero and negative exponents','Explain and evaluate zero and negative integer exponents on nonzero bases.',[
 'Positive exponents count repeated multiplication, but we need a consistent meaning for zero and negative exponents too. Follow a pattern: 2^3 = 8, 2^2 = 4, and 2^1 = 2. Every time the exponent decreases by one, divide the value by 2.',
 'Continue the same pattern. Dividing 2 by 2 gives 1, so 2^0 = 1. Dividing again gives 1/2, so 2^(-1) = 1/2. Another division gives 1/4, so 2^(-2) = 1/4. The rule follows the pattern rather than inventing a new operation.',
 'For a nonzero base b, b^0 = 1 and b^(-n) = 1/(b^n). A reciprocal is 1 divided by a number. A negative exponent means take the reciprocal; it does not mean put a negative sign in front of the answer.',
 'First evaluate the positive power in the denominator, then write the fraction. For 3^(-2), the denominator is 3 × 3 = 9, so the answer is 1/9. We exclude base zero because division by zero is undefined.'
],[ex('Evaluate 5^(-2).',['The exponent is negative, so rewrite the power as a reciprocal: 1/(5^2).','Evaluate the denominator: 5^2 = 25.','Write 1/25, a positive fraction. A negative exponent did not create a negative value.'],'1/25'),ex('Evaluate 7^0.',['The base is nonzero, so the zero-exponent rule applies.','Notice 7^2 / 7^2 = 1, and subtracting those exponents gives 7^0.','Therefore 7^0 must equal 1, not 0.'],'1')],{...negative('g',3,-2),steps:['Is the exponent zero or negative?','For a negative exponent, move the power into a denominator.','Calculate that denominator and write the reciprocal.']},[[2,-3],[10,-2],[6,0],[4,-2],[5,-1],[3,-3]].map((v,i)=>negative(`p${i+1}`,...v)),note('Explain why 2^(-3) is 1/8 rather than -8. Show a decreasing-exponent pattern.','Starting with 2^2 = 4, dividing by 2 each time gives 2, 1, 1/2, 1/4, 1/8. Thus 2^(-3) is 1/8. The negative exponent describes a reciprocal, not a negative value.')),
pack('scientific-notation','Writing scientific notation','Express large and small positive numbers using a coefficient and a power of ten.',[
 'Scientific notation is a compact way to write very large or very small numbers. It has the form a × 10^n, where a is at least 1 but less than 10 and n is an integer. The first number is called the coefficient.',
 'For a large number, move the decimal left until only one nonzero digit remains before it. Count the places moved. That count becomes a positive exponent, because multiplying by a positive power of ten restores the original large value.',
 'For a small number between zero and one, move the decimal right until the coefficient is at least 1. Use a negative exponent. Multiplying by a negative power of ten makes the coefficient smaller again. Leading zeros help locate the decimal; they do not become significant digits in the coefficient.',
 'Always check two things: is the coefficient in the required range, and does multiplying by the stated power return the starting value? For typed answers use a x 10^n. For example, 0.004 is 4 x 10^-3 because 4 divided by 1,000 is 0.004.'
],[ex('Write 72,000 in scientific notation.',['Place the decimal after the first nonzero digit to get 7.2.','The decimal moved four places left, so restoring the value requires multiplying by 10^4.','Check: 7.2 × 10,000 = 72,000, and 7.2 is between 1 and 10.'],'7.2 x 10^4'),ex('Write 0.00056 in scientific notation.',['Move the decimal right four places to get 5.6.','Use exponent -4 because the original value is smaller than 1.','Check: 5.6 × 0.0001 = 0.00056.'],'5.6 x 10^-4')],{...notation('g','480,000',4.8,5),steps:['Find a coefficient between 1 and 10.','Count the decimal places from the original position.','Choose the sign that makes the power restore the original size.']},[['36,000',3.6,4],['0.00072',7.2,-4],['8,100,000',8.1,6],['0.006',6,-3],['920',9.2,2],['0.0000095',9.5,-6]].map((v,i)=>notation(`p${i+1}`,...v)),note('Write 0.0038 in scientific notation and explain the negative exponent.','0.0038 = 3.8 x 10^-3. I moved the decimal three places right to get 3.8. Multiplying 3.8 by 1/1,000 returns the original value, so the exponent must be negative.')),
pack('equations-both-sides','Equations with variables on both sides','Keep an equation balanced while collecting variables and solving for x.',[
 'An equation says that two expressions have equal values. Think of a balanced scale. If you add, subtract, multiply, or divide one side, you must do the same to the other side to preserve the equality. Solving means finding the value that makes the original statement true.',
 'When x appears on both sides, collect the x terms on one side first. Subtracting the smaller x term from both sides often keeps the remaining coefficient positive. You are not simply moving a term across a symbol; you are performing the same operation on both complete sides.',
 'Next collect the constant numbers on the other side using addition or subtraction. Finally divide both sides by the coefficient of x. Write one balanced equation per line so that each change is easy to explain. These problems have a single solution.',
 'A check is part of the work. Substitute your value for every x in the original equation, then calculate each side separately. If they do not match, inspect your subtraction and division. The answer is not the number sitting next to x; it is the value of x itself.'
],[ex('Solve 5x + 4 = 2x + 19.',['Subtract 2x from both sides: 3x + 4 = 19. This gathers the variable terms.','Subtract 4 from both sides: 3x = 15. Then divide both sides by 3: x = 5.','Check in the original: 5(5) + 4 = 29 and 2(5) + 19 = 29.'],'5'),ex('Solve 7x + 2 = 3x + 26.',['Subtract 3x from each side to get 4x + 2 = 26.','Subtract 2 to get 4x = 24, then divide by 4 to get x = 6.','Substitution gives 44 on the left and 44 on the right, confirming the solution.'],'6')],{...equation('g',6,3,2,4),steps:['Subtract the smaller x term from each side.','Subtract the constant on the x side from both sides.','Divide by the remaining coefficient and check the original equation.']},[[4,5,1,7],[8,3,5,6],[9,2,3,4],[5,7,2,3],[7,4,3,8],[6,9,4,5]].map((v,i)=>equation(`p${i+1}`,...v)),note('Solve 8x + 5 = 3x + 30. Explain why each operation keeps the equation balanced.','Subtracting 3x from both sides gives 5x + 5 = 30. Subtracting 5 gives 5x = 25. Dividing both sides by 5 gives x = 5. The original sides both equal 45, so the solution checks.')),
pack('slope','Finding slope from two points','Calculate a constant rate of change using rise divided by run.',[
 'A line’s slope describes how much y changes for each one-unit increase in x. This is a rate of change. A positive slope rises as you move right; a negative slope falls as you move right. A horizontal line has zero slope because y does not change.',
 'An ordered pair is written (x, y). With two points, find the vertical change by subtracting the y-values. Find the horizontal change by subtracting the x-values. Divide vertical change by horizontal change: m = (y2 − y1)/(x2 − x1).',
 'The subtraction order must match. If you use the second point minus the first for y, do the same for x. Reversing both orders gives the same answer, but reversing only one changes the sign incorrectly. Writing both differences before calculating helps avoid that mistake.',
 'Slope can be a whole number, a fraction, or zero. A vertical line has zero horizontal change, so its slope is undefined, not zero. In this lesson every pair has different x-values, so division is possible. Interpret the sign before deciding whether your computed answer is sensible.'
],[ex('Find slope through (1, 2) and (4, 8).',['The vertical change is 8 − 2 = 6.','The horizontal change in the same order is 4 − 1 = 3.','Divide rise by run: 6/3 = 2. The line rises 2 units per unit right.'],'2'),ex('Find slope through (2, 7) and (6, 5).',['Calculate the y change: 5 − 7 = -2.','Calculate the x change in the same order: 6 − 2 = 4.','Slope is -2/4 = -1/2. The negative sign matches a line falling to the right.'],'-1/2')],{...slope('g',1,3,5,11),steps:['Label the first and second point consistently.','Find the y difference and the x difference in matching order.','Divide and simplify, then consider the sign.']},[[0,1,3,10],[2,8,6,0],[-2,1,2,3],[1,4,7,4],[-1,6,3,3],[3,-2,5,3]].map((v,i)=>slope(`p${i+1}`,...v)),note('Find the slope through (0, 6) and (4, 2). Explain what the sign tells you.','The rise is 2 − 6 = -4 and the run is 4 − 0 = 4. The slope is -1. As x increases by one, y decreases by one. That matches the second point being lower and to the right.')),
pack('linear-models','Using a slope-intercept model','Separate the starting amount from the constant rate in y = mx + b.',[
 'A linear model describes a quantity that changes at a constant rate. In y = mx + b, x is the input and y is the output. The number m tells how much y changes for each additional unit of x. The number b is the value of y when x is zero.',
 'Imagine a delivery service that charges a starting fee plus an amount per mile. The fee appears once as b. The per-mile rate is multiplied by the number of miles as mx. Keeping these roles separate prevents you from multiplying the starting fee by the distance.',
 'To use the model, replace x with the given input. Multiply first, then add the constant. Carry the units in your thinking even when the answer box asks for a number only. The output might represent dollars, liters, or another measured amount.',
 'A model depends on assumptions. A constant price per unit gives a straight-line relationship only while the rate stays the same. Before calculating, identify what the input counts and what the output measures. You can check the starting value by substituting zero: the mx term disappears and y equals b.'
],[ex('A ride costs $4 to start plus $3 per mile. What does a 5-mile ride cost?',['Let x be miles and y be total dollars. The model is y = 3x + 4.','Substitute x = 5: y = 3(5) + 4 = 15 + 4.','The total is $19. The $4 start fee was added only once.'],'19'),ex('A tank starts with 12 liters and gains 2 liters per minute. How much after 7 minutes?',['The starting amount is 12 and the rate is 2, so y = 2x + 12.','Substitute the elapsed minutes: y = 2(7) + 12.','Adding 14 and 12 gives 26 liters. This is greater than the starting amount.'],'26')],{...model('g',4,6,3,'A rental charges $6 initially and $4 per hour; x is hours and y is dollars.'),steps:['Identify the rate and the starting amount.','Replace x with the given number of hours.','Multiply before adding the one-time amount.']},[[2,5,8,'A delivery costs $5 plus $2 per kilometer; x is kilometers.'],[3,10,6,'A tank starts with 10 liters and gains 3 liters per minute; x is minutes.'],[5,7,4,'A rental costs $7 plus $5 per hour; x is hours.'],[4,2,9,'A savings jar starts with $2 and gains $4 per week; x is weeks.'],[6,12,0,'An event has a $12 setup fee and $6 per attendee; x is attendees.'],[2,15,12,'A plant is 15 cm tall and grows 2 cm per week in this model; x is weeks.']].map((v,i)=>model(`p${i+1}`,...v)),note('A bike rental uses y = 5x + 8, where x is hours and y is dollars. Explain both numbers and find the cost for 4 hours.','The 5 is the hourly rate and the 8 is a one-time fee. For 4 hours, y = 5(4) + 8 = 28 dollars. Charging the fee four times would not match this model.')),
pack('functions','Deciding whether a relation is a function','Check whether each input has exactly one output.',[
 'A function is a rule that assigns exactly one output to each input in its domain. You can imagine a reliable machine: for a particular input, the rule cannot produce two different outputs at the same time. It is the input-to-output assignment that matters.',
 'Ordered pairs record inputs and outputs. In (3, 8), the input is 3 and the output is 8. To check a list, look through the first coordinates. If an input repeats, compare its outputs. A repeated input with different outputs means the relation is not a function.',
 'Different inputs are allowed to have the same output. For example, two people can have the same age even though each person has one age at a particular moment. Repeating a y-value is not the problem. It is a single x-value leading to conflicting y-values that breaks the rule.',
 'A table with no repeated inputs is a function because each listed input has just one output. Identical repeated pairs also do not create a conflict. Do not assume the points must lie on a straight line: functions can be linear or nonlinear. This lesson checks the definition using ordered pairs.'
],[ex('Is {(1, 4), (2, 4), (3, 9)} a function?',['Read the inputs: 1, 2, and 3. None has two different listed outputs.','The output 4 appears twice, but it belongs to different inputs. This is allowed.','Every input has one output, so the relation is a function.'],'yes'),ex('Is {(2, 5), (4, 7), (2, 8)} a function?',['Read the first coordinates. Input 2 appears twice.','Compare its outputs: one pair gives 5 and the other gives 8.','One input has two different outputs, so this relation is not a function.'],'no')],{...fun('g',[[0,2],[1,5],[0,7]],false),steps:['List only the first coordinates to identify repeated inputs.','For any repeated input, compare the corresponding outputs.','Decide whether one input is assigned conflicting outputs.']},[[[[1,3],[2,6],[3,9]],true],[[[2,4],[2,7],[5,9]],false],[[[-1,1],[0,1],[1,1]],true],[[[0,2],[3,5],[0,8]],false],[[[1,2],[1,2],[4,8]],true],[[[-2,4],[2,4],[-2,5]],false]].map(([pairs,a],i)=>fun(`p${i+1}`,pairs,a)),note('Create one relation that is a function and one that is not. Explain the difference using inputs and outputs.','The pairs (1, 2), (2, 2), (3, 4) form a function: each input has one output. The pairs (1, 2), (1, 5), (3, 4) do not because input 1 has two outputs. Shared outputs alone are allowed.')),
pack('systems-substitution','Solving a system by substitution','Find a point that satisfies two linear equations at the same time.',[
 'A system is a set of equations that must be true together. With two equations involving x and y, a solution is an ordered pair that works in both. On a graph, that point lies on both lines. Solving only one equation does not guarantee a shared solution.',
 'Substitution replaces an expression with an equal expression. If the first equation says y = 2x + 1, every y in the other equation can be replaced with 2x + 1. When both equations already have y alone, simply set their right sides equal.',
 'The new equation contains only x. Gather the x terms, gather constants, and divide to find x. Then substitute that value into either original equation to find y. Keep track of the order: an ordered pair is written x first, then y.',
 'Check the pair in both original equations. Each must produce the same y-value. Two lines can also be parallel or identical, but this lesson uses systems with one intersection. The different slopes in these examples guarantee a single meeting point, so there is one pair to find.'
],[ex('Solve y = 2x + 1 and y = x + 5.',['Both expressions equal y, so set 2x + 1 = x + 5.','Subtract x and then 1 to get x = 4. Substitute into the first equation: y = 2(4) + 1 = 9.','Check the other equation: 4 + 5 = 9. Both give the point (4, 9).'],'4, 9'),ex('Solve y = 3x + 2 and y = x + 10.',['Set the expressions equal: 3x + 2 = x + 10.','Subtract x and 2: 2x = 8, so x = 4. Then y = 3(4) + 2 = 14.','Check the second equation: 4 + 10 = 14. The shared point is (4, 14).'],'4, 14')],{...system('g',4,1,2,7),steps:['Set the two expressions for y equal to each other.','Solve the resulting equation for x.','Substitute into an original equation to find y, and check both.']},[[2,3,1,8],[3,1,1,9],[4,2,2,14],[5,1,3,7],[3,4,2,6],[6,2,2,18]].map((v,i)=>system(`p${i+1}`,...v)),note('Solve y = 4x + 2 and y = 2x + 12. Explain why setting the expressions equal is allowed.','Both expressions represent the same y at the intersection. So 4x + 2 = 2x + 12, giving 2x = 10 and x = 5. Then y = 22. Both original equations produce 22 when x is 5.')),
pack('pythagorean-theorem','Finding a right triangle’s hypotenuse','Use a² + b² = c² to find the longest side of a right triangle.',[
 'A right triangle contains one 90-degree angle. The two sides touching that angle are the legs. The side opposite it is the hypotenuse, which is always the longest side. Identify these parts before choosing where to put numbers in a formula.',
 'The Pythagorean theorem says a² + b² = c² for a right triangle. Here a and b are the legs, and c is the hypotenuse. Squaring a side means multiplying its length by itself. Geometrically, the areas of squares on the legs add to the area of the square on the hypotenuse.',
 'When both legs are known, square each length and add the results. That sum is c², not c. Take the positive square root to obtain the actual length. Skipping the square root gives an area-sized number rather than a side length.',
 'The theorem applies to right triangles, not every triangle. Check that the answer is longer than each leg and that its square equals the sum of the leg squares. This lesson uses examples with whole-number lengths so you can concentrate on the reasoning rather than decimal rounding.'
],[ex('A right triangle has legs 3 cm and 4 cm. Find c.',['Identify c as the hypotenuse opposite the right angle.','Compute c² = 3² + 4² = 9 + 16 = 25.','Take the positive square root: c = 5 cm. Five is longer than both legs.'],'5'),ex('A right triangle has legs 5 cm and 12 cm. Find c.',['The known sides are legs, so add their squares.','Compute c² = 25 + 144 = 169.','Because 13 × 13 = 169, c = 13 cm. The side length is 13, not 169.'],'13')],{...triangle('g',6,8),steps:['Place the two leg lengths in a² + b².','Square each length and add to find c².','Take the positive square root and compare with the legs.']},[[8,15],[7,24],[9,12],[12,16],[20,21],[10,24]].map((v,i)=>triangle(`p${i+1}`,...v)),note('A rectangular field measures 9 m by 12 m. Find its diagonal and explain why a right-triangle rule works.','The corner of a rectangle is a right angle, so the diagonal is the hypotenuse of a right triangle with legs 9 and 12. Its square is 81 + 144 = 225. The diagonal is 15 m.')),
pack('translations','Translating points on a coordinate plane','Apply horizontal and vertical shifts without changing shape or size.',[
 'A translation slides a figure without turning it, reflecting it, or changing its size. Every point moves the same distance in the same direction. Corresponding side lengths and angles remain equal, so a translated figure is congruent to the original.',
 'A point is written (x, y). The x-coordinate measures horizontal position; the y-coordinate measures vertical position. Moving right increases x, while moving left decreases x. Moving up increases y, while moving down decreases y. Treat these as two separate calculations.',
 'A translation rule can be written (x, y) → (x + a, y + b). A positive a shifts right and a negative a shifts left. A positive b shifts up and a negative b shifts down. Apply the same rule to every vertex when translating a polygon.',
 'Be especially careful when the starting coordinates are negative. Adding to a negative coordinate can bring it toward zero or past zero. Check by imagining movement on number lines, not by changing signs at random. To reverse a translation, undo both shifts with their opposite movements.'
],[ex('Move (2, 3) left 5 units and up 4 units.',['Left changes x: 2 − 5 = -3.','Up changes y: 3 + 4 = 7.','Keep x first and y second. The image point is (-3, 7).'],'-3, 7'),ex('Move (-4, 1) right 6 units and down 3 units.',['Right adds to x: -4 + 6 = 2.','Down subtracts from y: 1 − 3 = -2.','The image is (2, -2). Reversing the two moves returns (-4, 1).'],'2, -2')],{...translation('g',1,-2,3,5),steps:['Change x by the horizontal movement only.','Change y by the vertical movement only.','Write the new pair in x, y order and mentally reverse the slide.']},[[2,4,3,-2],[-3,1,5,4],[6,-2,-4,3],[-5,-4,2,-3],[0,7,-6,-5],[4,0,-7,2]].map((v,i)=>translation(`p${i+1}`,...v)),note('Translate triangle A(0, 0), B(3, 0), C(0, 2) right 2 and up 1. Explain why its size is unchanged.','The new vertices are A(2, 1), B(5, 1), and C(2, 3). Every vertex received the same shift. The horizontal leg remains 3 units and the vertical leg remains 2 units, so the triangle has not been stretched.'))
];
