import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
assert.ok(existsSync(new URL('../workbook-core.js',import.meta.url)), 'Missing teach-first workbook core');
const { freshProgress, checkAnswer, recordAnswer, canFinish, normalize, hydrate, STORAGE_KEY } = await import('../workbook-core.js');
const p=freshProgress();
assert.equal(p.stage,0); assert.equal(p.unlocked,0); assert.equal(p.done,false);
assert.notEqual(STORAGE_KEY,'middle-school-mastery.v1','must not overwrite old records');
const q={id:'q1',accepted:['1/2'],answer:'1/2'};
assert.equal(checkAnswer(q,'0.5'),true); assert.equal(checkAnswer(q,''),false);
assert.equal(checkAnswer(q,'1/0'),false); assert.equal(checkAnswer(q,'0.5001'),false);
assert.equal(normalize('  −3  '),'-3');
recordAnswer(p,q,'99'); assert.equal(p.results.q1.correct,false); assert.equal(p.results.q1.firstCorrect,false);
recordAnswer(p,q,'1/2'); assert.equal(p.results.q1.correct,true); assert.equal(p.results.q1.firstCorrect,false); assert.equal(p.results.q1.attempts,2);
assert.equal(canFinish({practice:[q],notebook:{checklist:['Explain']}},p),false);
p.notebook='I divided the total into equal parts.';p.checklist=[true];
assert.equal(canFinish({practice:[q],notebook:{checklist:['Explain']}},p),true);
assert.deepEqual(hydrate(null).lessons,{});
assert.deepEqual(hydrate({lessons:{x:p}}).lessons.x,p);
console.log('workbook core: PASS (teach-first state, answer checking, correction history, completion, separate storage)');
